/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 06 13:46:29 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class example_ESTest extends example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      example example0 = new example();
      example0.inc();
      boolean boolean0 = example0.isNonNegative();
      assertEquals(1, example0.getCount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      example example0 = new example();
      example0.add((-1511));
      int int0 = example0.getCount();
      assertFalse(example0.isNonNegative());
      assertEquals((-1511), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      example example0 = new example();
      boolean boolean0 = example0.isNonNegative();
      assertEquals(0, example0.getCount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      example example0 = new example();
      example0.add((-1511));
      boolean boolean0 = example0.isNonNegative();
      assertEquals((-1511), example0.getCount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      example example0 = new example();
      int int0 = example0.getCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      example example0 = new example();
      example0.inc();
      int int0 = example0.getCount();
      assertEquals(1, int0);
  }
}
